### ISSUE TITLE
[Tutorial] - How to use NodeJS with MongoDB

### ISSUE THREAD

**Issue by ninefyi** [mongodbthailand/mongodbthailand.github.io#17]
- [ ] Create a tutorial on how to use MongoDB NodeJS driver to connect MongoDB
- [ ] Create a tutorial on how to catch exception errors.

**Comment by Fai** [comment]
Sawasdee ka K.Fyi! I hope you're doing well. I came across the repository and I'm really excited about contributing to it for Hacktoberfest. I noticed this issue and would love to take it up.

I've already gone through the issue description and I have some ideas and potential solutions in mind. I believe this would be a great opportunity for me to learn and contribute to the project as i already completed MongoDB Node.js Developer Path on MongoDB University and recently used MongoDB Node Driver as well as MongoError on my project.

Please let me know if the issue is still open and if I can start working on it. I'm looking forward to your guidance and feedback throughout the process.

Thank you for maintaining this project and for providing this opportunity for new contributors like me ka :)

**Comment by ninefyi** [comment]
Hi K. Fai, Please go ahead krub. /\

**Comment by champjss** [comment]
@Fai Thanks for greet content!
